[phases.setup]
nixPkgs = ["nodejs_24", "pnpm_10"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "PORT=3000 BASE_PATH=/ pnpm --filter @workspace/vanny-konveksi run build",
  "pnpm --filter @workspace/api-server run build"
]

[start]
cmd = "pnpm --filter @workspace/api-server run start"
